FROM python:3.11-slim

WORKDIR /app

# Tizim paketlari
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Python paketlari
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Loyiha fayllari
COPY . .

# Logs papkasi
RUN mkdir -p logs

CMD ["python", "main.py"]